---
fixtures:
  repositories:
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    rsync: https://github.com/simp/pupmod-simp-rsync
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib:  https://github.com/simp/puppetlabs-stdlib
  symlinks:
    clamav: "#{source_dir}"
