---
fixtures:
  repositories:
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    logrotate: "git://github.com/simp/pupmod-simp-logrotate"
    rsync: "git://github.com/simp/pupmod-simp-rsync"
    selinux: "git://github.com/simp/pupmod-simp-selinux"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
    compliance: "https://github.com/trevor-vaughan/pupmod-compliance"
  symlinks:
    clamav: "#{source_dir}"
