---
fixtures:
  repositories:
    common: "git://github.com/simp/pupmod-simp-common"
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    logrotate: "git://github.com/simp/pupmod-simp-logrotate"
    rsync: "git://github.com/simp/pupmod-simp-rsync"
    selinux: "git://github.com/simp/augeasproviders_grub"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
  symlinks:
    clamav: "#{source_dir}"
