# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
#
# https://puppet.com/docs/pe/2018.1/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# PE 2017.3     5.3      2.4.5  2018-12-31
# SIMP 6.3      5.5      2.4.5  TBD***
# PE 2018.1     5.5      2.4.5  2020-05 (LTS)***
# PE 2019.0     6.0      2.5.1  2019-08-31^^^
#
# *** = Modules created for SIMP 6.3+ are not required to support Puppet < 5.5

---
language: ruby
cache: bundler
sudo: false

stages:
  - check
  - spec
  - name: deploy
    if: 'tag IS present'

bundler_args: --without development system_tests --path .vendor

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm

before_install:
  - rm -f Gemfile.lock
  - for x in ${HOME}/.rvm/gems/*; do gem uninstall -I -x -i "${x}" -v '>= 1.17' bundler || true; gem uninstall -I -x -i "${x}@global" -v '>= 1.17' bundler || true; done
  - gem install -v '~> 1.17' bundler

global:
  - STRICT_VARIABLES=yes

jobs:
  include:
    - stage: check
      name: 'Syntax, style, and validation checks'
      rvm: 2.4.5
      env: PUPPET_VERSION="~> 5"
      script:
        - bundle exec rake check:dot_underscore
        - bundle exec rake check:test_file
        - bundle exec rake pkg:check_version
        - bundle exec rake metadata_lint
        - bundle exec rake pkg:compare_latest_tag
        - bundle exec rake pkg:create_tag_changelog
        - bundle exec rake lint
        - bundle exec puppet module build

    - stage: spec
      name: 'Puppet 5.3 (PE 2017.3)'
      rvm: 2.4.5
      env: PUPPET_VERSION="~> 5.3.0"
      script:
        - bundle exec rake spec

    - stage: spec
      rvm: 2.4.5
      name: 'Puppet 5.5 (SIMP 6.3, PE 2018.1)'
      env: PUPPET_VERSION="~> 5.5.0"
      script:
        - bundle exec rake spec

    - stage: spec
      name: 'Latest Puppet 5.x'
      rvm: 2.4.5
      env: PUPPET_VERSION="~> 5.0"
      script:
        - bundle exec rake spec

    - stage: spec
      name: 'Latest Puppet 6.x'
      rvm: 2.5.1
      env: PUPPET_VERSION="~> 6.0"
      script:
        - bundle exec rake spec

    - stage: deploy
      rvm: 2.4.5
      script:
        - true
      before_deploy:
        - "export PUPMOD_METADATA_VERSION=`ruby -r json -e \"puts JSON.parse(File.read('metadata.json')).fetch('version')\"`"
        - '[[ $TRAVIS_TAG =~ ^simp-${PUPMOD_METADATA_VERSION}$|^${PUPMOD_METADATA_VERSION}$ ]]'
      deploy:
        - provider: releases
          api_key:
            secure: "qL0Cqxyrrl4/2tyN3tVUD3ecjHMEyf9H5/9UY9Ibi2wr8REfiME5ss1DzZeUkpkA5b3iSry7X7p7qz6Hhkoaw6xYK840Mos70enm/Hqfv8BLnMX0GtirZGFkFU8Pa1BrdFdDf9gK/8PXpIV6KR3OMIeWmeUE11tR4QZv62769qf+snxY4EtGWje9xEUHaO1/kRk13NAToQdB2M9uD7B1x9mGZq5/UOB5NpNgjgz2zGubrdGX7ezf9lWFjWaDmbmWVtHDEuECBa+arxv2/FcqtHv67uCiORMZQ0fwg+QRPi8qqrGbLERKzebUM1igRcW9BoGXkdH7GY8+2rWEtJc0y13O9CCI0u64x+10BAgy2j+5S+LhJ4tQaByu32oc/Vqo9ueAoREIiBBS32INrFv7UqtmreN5UqaaXvumC/AGHVA0HbKy2pd6YtQTUyf0BpvKcY1G1keVAgfuOFViHeN1MGs3oHOPOTRhuYIyWmF8v/tncqIvA5bCgGZzBUTFUjwBpAMiYJmYNcDqUEFzUnJ2NE7YTLIo88uf5/ZgGYKM3SDmBS1Eh0g/Sk86ql2iQcfEKK6xLx7SHQbY1wA+5svClTlT41dJRmIeJSJuUwrTy5gS2MdEsOqobQRHrB5ZmZfglclLqMQ6TJ2luhC2d/bQ7Pi6YPJTrYSPAid1qXcqRIg="
          skip_cleanup: true
          on:
            tags: true
            condition: '($SKIP_FORGE_PUBLISH != true)'
        - provider: puppetforge
          user: simp
          password:
            secure: "m+u/Ub9vg2igdiTzpFvXk2WbbBAE0WJBRmegEhzyjkoeO7hJOvt1WSS9BmT+YLScNgM9IUczna4Tv2Gyp51Ydr+GqxktDlzOkACu6iZ4kOfx8Z9veCnYq4Og8eYmt0ghRDmXANCjECRdg1F6LajA9Ub9d/p6OVZYVV5wpWE07rMYrdq8un31Q9N6YnT9WUuMRtJj0eZzwdSNGKq+4IoPH7kY3QdWBjGPct23fe2BweB+8XuxqEA3olbUDCOyJnL6/j1VH0WGajoTLO7Q85S1Py+7vMaJYur+5i2VNGKNOeV/X8oKw/feSapaZBmQxvrUU+5C4heVe3HjDwOMG2nyhNKPoZd9E6XGE2B6kuLcY8djasMhThc7db9jL/OnPfpwFRhhUxTGkli4NVNZ0eS4nNxoBlKkkupAaun8zkwf0Y36yEUqeYbauXXRhqZECYeJOYQbiZSjXj9oNTvJOYwKSrowN7g58hbIrUzZkiQ4zsAEul7/JI/dmJzBaSzdfA2UTWrQnaMD/RpNgXdQpj+dmsklU4DTBhgJyQ4CzqzOCAucK4pXu9lczQpiGzUpWtvOIBukcOaGmsYJh+HwnPb6j+MEDWCpCkz0O2tazdNWtzqgk/uPWOAQKTY1+Tx82FI3ZIVWYDB30IDnxQLoIio42Ml+fBw5wj0O6H5CaFI4urg="
          on:
            tags: true
            condition: '($SKIP_FORGE_PUBLISH != true)'
