HOSTS:
  client6-1:
    repos:
      simp:
        url: https://dl.bintray.com/simp/4.2.0-Beta2
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://getfedora.org/static/0608B895.txt
    roles:
      - default
      - master
      - client
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
  client7-1:
    roles:
      - client
    repos:
      simp:
        url: https://dl.bintray.com/simp/5.1.0-Beta
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://getfedora.org/static/352C64E5.txt
    platform: el-7-x86_64
    box: centos/7
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type: aio
