---
HOSTS:
  el7:
    roles:
    - client
    - default
    - master
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      epel:
        mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
        gpgkeys:
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  el8:
    roles:
    - client
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      epel:
        mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch
        gpgkeys:
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  type: aio
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
